name = "key-gao-global"
main = "src/worker.ts"
compatibility_date = "2026-03-31"

[assets]
directory = "out"
binding = "ASSETS"
not_found_handling = "single-page-application"

routes = [
  { pattern = "key.gao.global", custom_domain = true }
]
